version: '3'

networks:
  transcendence:
    name: transcendence

services:
  nginx:
    image: nginx:transcendence
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    networks:
        - transcendence
    ports:
      - 8080:8080

  django:
    image: django:transcendence
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: django
    networks:
      - transcendence
    ports:
      - 8000:8000
