version: '3'

services:
  django:
    build: .
    container_name: django
    image: django:transcendence
    volumes:
      - media-volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence
    env_file:
      - .env
    ports:
      - 8000:8000

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    image: nginx:transcendence
    volumes:
      - media-volume:/var/www/html/media
    depends_on:
      - django
    networks:
      - transcendence
    ports:
      - 5000:5000

  db:
    image: postgres
    container_name: postgres
    healthcheck:
      test: pg_isready
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - transcendence
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGPORT: ${SQL_PORT}
      PGUSER: ${SQL_USER}
      PGDATABASE: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    ports:
      - ${SQL_PORT}:${SQL_PORT}

networks:
  transcendence:
    name: transcendence

volumes:
  db-volume:
    name: db-volume
  media-volume:
    name: media-volume
